backend:
  name: github
  repo: neuracampus/neuracampus.github.io
  branch: main
  base_url: https://your-netlify-site-name.netlify.app # This tells Decap where to find the login server
  auth_endpoint: /external/auth/github
  app_id: Ov23likxlNdvvldcNrnS

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "blogs"
    label: "Blogs"
    folder: "content/blogs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }
