backend:
  name: github
  repo: neuracampus/neuracampus.github.io
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "jobs"
    label: "Jobs"
    folder: "content/jobs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Job Title", name: "title", widget: "string" }
      - { label: "Company Name", name: "company", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "CTC", name: "ctc", widget: "string" }
      - { label: "Apply Link", name: "apply", widget: "string" }
      - { label: "Company Logo", name: "logo", widget: "image" }
      - { label: "Job Description", name: "body", widget: "markdown" }

  - name: "blogs"
    label: "Blogs"
    folder: "content/blogs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Content", name: "body", widget: "markdown" }

